
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LOAITHUTHU
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LOAITHUTHU()
    {

        this.THUTHUs = new HashSet<THUTHU>();

        this.THUTHUQUYENs = new HashSet<THUTHUQUYEN>();

    }


    public int MALOAI { get; set; }

    public string TENLOAI { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<THUTHU> THUTHUs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<THUTHUQUYEN> THUTHUQUYENs { get; set; }

}

}
