
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MUONTRA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MUONTRA()
    {

        this.CHITIETMUONTRAs = new HashSet<CHITIETMUONTRA>();

    }


    public int MAMUON { get; set; }

    public Nullable<System.DateTime> NGAYMUON { get; set; }

    public Nullable<System.DateTime> HANTRA { get; set; }

    public Nullable<System.DateTime> NGAYTRATHUCTE { get; set; }

    public Nullable<bool> TRANGTHAIMUON { get; set; }

    public Nullable<bool> TRANGTHAITRA { get; set; }

    public Nullable<bool> DAXOA { get; set; }

    public string GHICHU { get; set; }

    public Nullable<int> ID { get; set; }

    public Nullable<int> MATHUTHU { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIETMUONTRA> CHITIETMUONTRAs { get; set; }

    public virtual DOCGIA DOCGIA { get; set; }

    public virtual THUTHU THUTHU { get; set; }

}

}
