//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public int MAPHIEUNHAP { get; set; }
        public Nullable<int> MANHACUNGCAP { get; set; }
        public Nullable<int> MASACH { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string SOLUONGNHAP { get; set; }
        public Nullable<bool> DAXOA { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
