
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SACH
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SACH()
    {

        this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();

        this.CHITIETMUONTRAs = new HashSet<CHITIETMUONTRA>();

    }


    public int MASACH { get; set; }

    public string TENSACH { get; set; }

    public string TACGIA { get; set; }

    public Nullable<int> SOLUONGTON { get; set; }

    public string MOTA { get; set; }

    public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }

    public Nullable<int> SOLUONGMUON { get; set; }

    public Nullable<int> LUOTXEM { get; set; }

    public Nullable<bool> DAXOA { get; set; }

    public string HINHANH { get; set; }

    public Nullable<int> MANHAXUATBAN { get; set; }

    public Nullable<int> MATHELOAI { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }

    public virtual NHAXUATBAN NHAXUATBAN { get; set; }

    public virtual THELOAI THELOAI { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIETMUONTRA> CHITIETMUONTRAs { get; set; }

}

}
