
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class THUTHU
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public THUTHU()
    {

        this.MUONTRAs = new HashSet<MUONTRA>();

    }


    public int MATHUTHU { get; set; }

    public string TENTHUTHU { get; set; }

    public string EMAIL { get; set; }

    public string SODIENTHOAI { get; set; }

    public string USERNAME { get; set; }

    public string PASSWORD { get; set; }

    public Nullable<bool> TINHTRANG { get; set; }

    public Nullable<int> MALOAI { get; set; }



    public virtual LOAITHUTHU LOAITHUTHU { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MUONTRA> MUONTRAs { get; set; }

}

}
