
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VIPHAM
{

    public int MAVIPHAM { get; set; }

    public Nullable<int> ID { get; set; }

    public string LYDOVP { get; set; }

    public string HINHTHUCXULY { get; set; }



    public virtual DOCGIA DOCGIA { get; set; }

}

}
